FROM node:21-alpine

ARG NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT=master \
    NEXT_PUBLIC_CONTENTFUL_SPACE_ID=hwmj2aa7yfke \ 
    NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=elBQkd243NoCblirgfeQ9s_-P_NdJGYwNzVokcJdu5Q \
    NEXT_PUBLIC_CONTENTFUL_CONTENT_TYPE_BLOG=blog \
    NEXT_PUBLIC_CONTENTFUL_CONTENT_TYPE_CAREER=career 

ENV NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT=$NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT \
    NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=$NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN \
    NEXT_PUBLIC_CONTENTFUL_SPACE_ID=$NEXT_PUBLIC_CONTENTFUL_SPACE_ID \
    NEXT_PUBLIC_CONTENTFUL_CONTENT_TYPE_BLOG=$NEXT_PUBLIC_CONTENTFUL_CONTENT_TYPE_BLOG \
    NEXT_PUBLIC_CONTENTFUL_CONTENT_TYPE_CAREER=$NEXT_PUBLIC_CONTENTFUL_CONTENT_TYPE_CAREER

# Set working directory
WORKDIR /contentful-cms-blogs

# Copy package.json and package-lock.json separately to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install

#Copy environment 
# COPY .env.local ./

# Copy the rest of the application code
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]